name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Lint
        uses: aglipanci/laravel-pint-action@0.1.0
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Linting

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: "8.1"
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Execute tests
      run: ./vendor/bin/phpunit